# Numpy_Complete_Reference

<b>1. Create 1D numpy array

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [4]:
b = np.arange(1, 6)
b

array([1, 2, 3, 4, 5])

<b> 2. Print dimensions of the numpy array

In [5]:
c = np.array([1, 2, 3, 4, 5])
c.ndim

1

<b>3. Print shape of the numpy array

In [8]:
c = np.array([1, 2, 3, 4, 5])
c.shape

(5,)

<b>4. Create 2D array and print dimensions and shape of the array

In [9]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
print('Dimensions : ',a.ndim)
print('Shape : ',a.shape)

Dimensions :  2
Shape :  (2, 5)


<b>5. Create 3D array and print dimensions and shape of the array

In [11]:
a = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]]])
print('Dimensions : ', a.ndim)
print('Shape : ', a.shape)

Dimensions :  3
Shape :  (2, 2, 5)


<b>6. Print no. of rows or length of the numpy matrix

In [12]:
a = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]]])
print('No. of rows / length of matrix : ', len(a))

No. of rows / length of matrix :  2


<b>7. Create a numpy array starting from 5 to 50 and step size of 3

In [13]:
a = np.arange(5, 50, 3)
a

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

<b>8. Create numpy array in linear space, from 0 to 1 and 6 points

In [14]:
a = np.linspace(0, 1, 6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

<b>9. Create numpy arrays with all values 1

In [15]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
b = np.ones((2, 2, 2))
b

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

<b>10. Create numpy arrays with all values as zeros

In [17]:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
b = np.zeros((2, 2, 2))
b

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

<b>11. Create identity matrices

In [19]:
a = np.eye(3) #3 no of diagonal elements
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
b = np.eye(3, 2) # 3 no. of rows and 2 no. of columns
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [22]:
b = np.eye(1, 5) # 1 no. of rows and 5 no. of columns
b

array([[1., 0., 0., 0., 0.]])

<b>12. Create a matrix provided diagonal elements

In [24]:
a = np.diag([1, 2, 3, 4]) # input is list of diagonal elements
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
b = np.diag([2, 10, 500])
b

array([[  2,   0,   0],
       [  0,  10,   0],
       [  0,   0, 500]])

<b>13. Extract diagonal elements from matrices

In [33]:
a = np.diag([1, 2, 3, 4])
print(a)
print('\n')
print(np.diag(a))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


[1 2 3 4]


In [35]:
b = np.diag([2, 10, 500])
print(b)
print('\n')
print(np.diag(b))

[[  2   0   0]
 [  0  10   0]
 [  0   0 500]]


[  2  10 500]


<b>14. Generate matrices with random numbers (uniform distribution)

In [36]:
a = np.random.rand(4)
a

array([0.54776587, 0.78806317, 0.51236099, 0.05251341])

In [38]:
b = np.random.rand(4, 2)
b

array([[0.30530098, 0.31643708],
       [0.48944876, 0.22523917],
       [0.01039548, 0.1551407 ],
       [0.35839265, 0.57419065]])

<b>15. Generate random numbers from normal distribution

In [41]:
a = np.random.randn(10)
a

array([-0.99993715,  0.41573644,  1.04327494, -0.51141506, -0.89002614,
        0.46811332,  0.22464173, -1.70930578,  0.64432227,  1.3117213 ])

In [40]:
b = np.random.randn(4, 2)
b

array([[-1.54873591, -0.68623073],
       [-1.85562512,  0.74270906],
       [ 0.8270639 , -2.62277133],
       [-0.07711489, -1.97999503]])

<b>16. Find the datatype of the numpy matrix (Float, Int, Bool, String)

In [43]:
a = np.random.rand(4)
print(a)
print('\n')
print('Datatype : ', a.dtype)

[0.32835631 0.3120526  0.35946761 0.54623568]


Datatype :  float64


In [49]:
d = np.array([1, 2, 3, 4, 5])
print(d)
print('\n')
print('Datatype : ', d.dtype)

[1 2 3 4 5]


Datatype :  int32


In [46]:
b = np.array([True, False, False, True, True])
print(b)
print('\n')
print('Datatype : ', b.dtype)

[ True False False  True  True]


Datatype :  bool


In [48]:
c = np.array(['ram', 'sham', 'bob', 'tim'])
print(c)
print('\n')
print('Datatype : ', c.dtype)

['ram' 'sham' 'bob' 'tim']


Datatype :  <U4


<b>17. Create a numpy array with different datatypes

In [44]:
a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
b = np.arange(10, dtype='int64')
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

<b>18. Given a matrix print diagonal elements without using 'diag' function

In [51]:
a = np.diag([1, 2, 3, 4])
print(a)
print('\n')
print('First diagonal element : ', a[0, 0])
print('Second diagonal element : ', a[1, 1])
print('Third diagonal element : ', a[2, 2])
print('Fourth diagonal element : ', a[3, 3])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


First diagonal element :  1
Second diagonal element :  2
Third diagonal element :  3
Fourth diagonal element :  4


<b>19. Update values of diagonal elements of a matrix

In [54]:
a = np.diag([1, 2, 3, 4, 5])
print('Before updating diagonal elements : ')
print(a)
print('\n')
a[0, 0] = 10
a[1, 1] = 20
a[2, 2] = 30
a[3, 3] = 40
a[4, 4] = 50
print('After updating diagonal elements : ')
print(a)

Before updating diagonal elements : 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


After updating diagonal elements : 
[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


<b>20. Given 1D array print elements starting from 2nd position till end with step size of 2 (slicing)

In [55]:
a = np.arange(20)
print(a)
print('\n')
print(a[1::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[ 1  3  5  7  9 11 13 15 17 19]


<b>21. Given 1D array, update sliced values with 100(Update sliced elements)

In [60]:
a = np.arange(20)
print('Given numpy array :')
print(a)

print('\nBefore update :')
print(a[1::2])

a[1::2] = 100
print('\nAfter update :')
print(a)

Given numpy array :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Before update :
[ 1  3  5  7  9 11 13 15 17 19]

After update :
[  0 100   2 100   4 100   6 100   8 100  10 100  12 100  14 100  16 100
  18 100]


<b>22. Given 2 matrices update values of few elements from one matrix to other matrix(Broadcasting)

In [71]:
# first 5 elements of matrix 'a' should be updated with last 5 elements of matrix 'b'
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

a[0:5] = b[5:]
print(a)

[ 60  70  80  90 100   6   7   8   9  10]


<b>23. Give examples of direct copy and using copy() function. Also use of function shares_memory()

In [80]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

c = a[3:]

print('Both matrix shares same memory? :', np.shares_memory(c, a))

Both matrix shares same memory? : True


In [81]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

c = a[3:].copy() # used copy() function to share separate memory

print('Both matrix shares same memory? :', np.shares_memory(c, a))

Both matrix shares same memory? : False


<b>24. Generate 15 random integers in the range 0 to 20

In [82]:
a = np.random.randint(0, 20, 15)
print(a)

[ 4  6  6 17 10  2 16  4 13  0 12 18  7 11  5]


<b>25. Given a list filter elements which are divisible by 2 using mask() function

In [83]:
a = np.random.randint(0, 20, 15)
print(a)

mask = (a % 2 == 0)
extract = a[mask]
print(extract)

[11 14  9 10 12  3  0  5  5  3 16  0 10  7 10]
[14 10 12  0 16  0 10 10]


<b>26. Given a list all even numbers should be updated with '-1'

In [84]:
a = np.random.randint(0, 20, 15)
print(a)

mask = (a % 2 == 0)
a[mask] = -1
print(a)

[19  4  3 15  8 18  6  9 10  6  1 14 10  2 12]
[19 -1  3 15 -1 -1 -1  9 -1 -1  1 -1 -1 -1 -1]


<b>27. Given a list copy few elements with indexes to other list

In [85]:
a = np.arange(10)
print(a)
print('\n')
b = a[[1, 2, 1, 3, 6, 5]]
print(b)

[0 1 2 3 4 5 6 7 8 9]


[1 2 1 3 6 5]


<b>28. Given a list assign value to selected indexed values

In [87]:
a = np.arange(10)
print(a)
print('\n')
a[[1, 3, 5, 7]] = -200
print(a)

[0 1 2 3 4 5 6 7 8 9]


[   0 -200    2 -200    4 -200    6 -200    8    9]


<b>29. Perform mathematical operations on all elements of array

In [95]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = a + 10
print(b)
print('\n')

c = a * 5
print(c)
print('\n')

d = (a * 5) + 5
print(d)
print('\n')

e = a**2
print(e)

[11 12 13 14 15 16 17 18 19 20]


[ 5 10 15 20 25 30 35 40 45 50]


[10 15 20 25 30 35 40 45 50 55]


[  1   4   9  16  25  36  49  64  81 100]


In [96]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print(a - b)

[ 9 18 27 36 45]


In [97]:
a = np.ones(4) * 2
b = np.zeros(4) + 5

a + b

array([7., 7., 7., 7.])

In [99]:
c = np.diag([1, 2, 3])
print(c)
print('\n')
print(c * c )
print('\n')
print(c.dot(c))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


[[1 0 0]
 [0 4 0]
 [0 0 9]]


[[1 0 0]
 [0 4 0]
 [0 0 9]]


<b>30. Perform different element-wise comparison operations on two numpy arrays

In [102]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 2, 1])
c = np.array([1, 2, 5, 6, 7])

print(a == b)
print('\n')

print(a == c)
print('\n')

print(a < b)

[False False False False False]


[ True  True False False False]


[ True  True  True False False]


<b>31. Perform different array-wise comparisons

In [103]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 2, 1])
c = np.array([1, 2, 3, 4, 5])

print(np.array_equal(a, b))
print(np.array_equal(a, c))

False
True


<b>32. Perform few logical operations on numpy arrays

In [107]:
a = np.array([1, 0, 1, 0], dtype=bool)
b = np.array([1, 1, 0, 0], dtype=bool)

print(np.logical_and(a, b))
print('\n')
print(np.logical_or(a, b))

[ True False False False]


[ True  True  True False]


<b>33. Perform 'sin', 'cos', 'exp', 'log' operations on the elements of numpy arrays

In [109]:
a = np.arange(5)
print(a)
print('\n')

print(np.sin(a))
print('\n')

print(np.cos(a))
print('\n')

print(np.log(a))
print('\n')

print(np.exp(a))

[0 1 2 3 4]


[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


[      -inf 0.         0.69314718 1.09861229 1.38629436]


[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


C:\Users\shashi\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in log
  # This is added back by InteractiveShellApp.init_path()


<b>34. Perform 'sum' operation on the matrices

In [111]:
a = np.array([1, 2, 3, 4, 5])
print(np.sum(a))
print(a.sum())

15
15


In [114]:
b = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(b)
print('\n')
print(b.sum(axis=0)) #column-wise sum
print('\n')
print(b.sum(axis=1)) #row-wise sum

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[ 7  9 11 13 15]


[15 40]


<b>35. Find min and max values of the arrays/matrices

In [115]:
a = np.array([6, 3, 9, 10, 2, 8])
print(a.min())
print('\n')
print(a.max())

2


10


In [116]:
b = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(b)
print('\n')

print(b.min())
print('\n')

print(b.max())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


1


10


<b>36. Find index values of min and max values in arrays/matrices

In [118]:
a = np.array([6, 3, 9, 10, 2, 8])
print(a.argmin())
print('\n')
print(a.argmax())

4


3


In [119]:
b = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(b)
print('\n')

print(b.argmin())
print('\n')

print(b.argmax())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


0


9


<b>37. Perform logical 'all' and 'any' operations on arrays

In [120]:
a = np.array([True, False, True, False])
b = np.array([True, True, True, True])

print(np.all(a))
print('\n')

print(np.any(a))
print('\n')

print(np.all(b))
print('\n')

False


True


True




In [121]:
c = np.array([1, 0, 1, 1])
d = np.array([1, 1, 1, 1])

print(np.all(c))
print('\n')

print(np.any(c))
print('\n')

print(np.all(d))
print('\n')

False


True


True




In [123]:
a = np.zeros((5, 5))
print(a)
print('\n')

print(np.any(a != 0))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


False


In [124]:
a = np.ones((5, 5)) + 10
print(a)
print('\n')

print(np.all(a > 10))

[[11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]]


True


In [126]:
c = np.array([1, 2, 3, 4, 5])
print(np.all(a == a))

True


In [128]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

<b>38. Find out 'mean', 'median', 'std dev' of elements of arrays/matrices

In [134]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(a)
print('\n')
print(b)
print('\n')

print(a.mean())
print(b.mean())
print('\n')

print(np.mean(a))  # alternate way for mean()
print(np.mean(b))
print('\n')

print(np.median(a))
print(np.median(b))
print('\n')

print(a.std())
print(b.std())

[1 2 3 4 5]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


3.0
5.5


3.0
5.5


3.0
5.5


1.4142135623730951
2.8722813232690143


In [136]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(a)
print('\n')

print(np.median(a, axis=0)) #column-wise median
print(np.median(a, axis=1)) #row-wise median

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[3.5 4.5 5.5 6.5 7.5]
[3. 8.]


<b>39. Create a sparse matrix

In [140]:
from scipy import sparse
a = np.array([[1, 0, 0, 2, 0],[0, 4, 0, 0, 0]])
print(a)
print('\n')
sp = sparse.csr_matrix(a)  # csr -> compressed sparse row
print(sp)

[[1 0 0 2 0]
 [0 4 0 0 0]]


  (0, 0)	1
  (0, 3)	2
  (1, 1)	4


<b>40. Reshape given matrix

In [146]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(a)
print('\n')

b = a.reshape(10, 2)
print(b)
print('\n')

c = a.reshape(2, 10)
print(c)
print('\n')

d = a.reshape(4, 5)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [148]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(a)
print('\n')

b = a.reshape(2, -1) # 2 columns and as many as columns needed
print(b)
print('\n')

c = a.reshape(-1, 2)  # 2 rows and as many as columns needed
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


<b>41. Transpose a vector/matrix

Transpose operation in linear algebra is, where the column and row indices of each elements are swapped.

In [150]:
a = np.array([[1, 2, 3, 4, 5, 6]])
print('Before transpose : ')
print(a)
print('\n')

print('After transpose : ')
print(a.T)

Before transpose : 
[[1 2 3 4 5 6]]


After transpose : 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


<b>42. Flatten matrix or transform into 1D array

In [152]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(a)
print('\n')

print(a.flatten())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[ 1  2  3  4  5  6  7  8  9 10]


<b>43. Find the rank of the matrix

In [154]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10], [11, 22, 33, 44, 55]])
print(a)
print('\n')

print(np.linalg.matrix_rank(a))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 22 33 44 55]]


2


<b>44. Find the determinant of the matrix

In [156]:
a = np.array([[1, 2, 3],[6, 7, 8], [11, 22, 33]])
print(a)
print('\n')

print(np.linalg.det(a))

[[ 1  2  3]
 [ 6  7  8]
 [11 22 33]]


1.526556658859582e-15


<b>45. Calculate trace of the matrix

Trace : Sum of diagonal elements of the matrix

In [157]:
a = np.array([[1, 2, 3],[6, 7, 8], [11, 22, 33]])
print(a)
print('\n')

print(a.trace())

[[ 1  2  3]
 [ 6  7  8]
 [11 22 33]]


41


<b>46. Find Eigen values and Eigen vectors of any matrix

In [158]:
a = np.array([[1, 2, 3],[6, 7, 8], [11, 22, 33]])
print(a)
print('\n')

eigenvalues, eigenvectors = np.linalg.eig(a)
print('Eigen values : ', eigenvalues)
print('\n')

print('Eigen vactors : ', eigenvectors)

[[ 1  2  3]
 [ 6  7  8]
 [11 22 33]]


Eigen values :  [ 3.97418814e+01 -4.47523611e-16  1.25811860e+00]


Eigen vactors :  [[-0.08762418 -0.40824829  0.05063647]
 [-0.25156383  0.81649658 -0.82896662]
 [-0.96386599 -0.40824829  0.55700115]]


<b>47. Invert a given matrix

In [159]:
a = np.array([[1, 2, 3],[6, 7, 8], [11, 22, 33]])
print(a)
print('\n')

print(np.linalg.inv(a))

[[ 1  2  3]
 [ 6  7  8]
 [11 22 33]]


[[ 3.60287970e+16  8.07434927e-17 -3.27534518e+15]
 [-7.20575940e+16  6.00000000e-01  6.55069037e+15]
 [ 3.60287970e+16 -4.00000000e-01 -3.27534518e+15]]


<b>48. Load text file 'populations.txt' and perform below operations,

1. Load text file 'populations.txt' using numpy
2. Discard year column
3. Find column-wise mean, std-dev
4. Which specis has highest populationeach year?

In [161]:
# Load text file 'populations.txt' using numpy

data = np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [163]:
# store values to corresponding variable
year, hare, lynx, carrot = data.T
print('Year : ')
print(year)
print('\n')

print('Hare : ')
print(hare)
print('\n')

print('Lynx : ')
print(lynx)
print('\n')

print('Carrot : ')
print(carrot)

Year : 
[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


Hare : 
[30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]


Lynx : 
[ 4000.  6100.  9800. 35200. 59400. 41700. 19000. 13000.  8300.  9100.
  7400.  8000. 12300. 19500. 45700. 51100. 29700. 15800.  9700. 10100.
  8600.]


Carrot : 
[48300. 48200. 41500. 38200. 40600. 39800. 38600. 42300. 44500. 42100.
 46000. 46800. 43800. 40900. 39400. 39000. 36700. 41800. 43300. 41300.
 47300.]


In [164]:
# Discard 'year' column
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [168]:
# Find 'mean' of each column
populations.mean(axis=0)  # axis=0, means column-wise

array([34080.95238095, 20166.66666667, 42400.        ])

In [169]:
# Find 'standard deviation' of each column
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [171]:
# Which specis has highest populationeach year?
np.argmax(populations, axis=1)  # axis=1, means row-wise operation

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)