In [1]:
#create simple numpy array and print
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [2]:
#create and print numbers in range of 10
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [3]:
a = np.array([1, 2, 3, 4, 5]) #1D array

#dimensions
a.ndim

1

In [4]:
a = np.array([1, 2, 3, 4, 5]) #1D array

#shape
a.shape

(5,)

In [11]:
#create 2D array
b=np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print('dimensions : ',b.ndim)
print('shape : ',b.shape)
print('size : ',b.size) #size is the number of total elements
print('length : ',len(b)) #size of the first dimension

dimensions :  2
shape :  (2, 4)
size :  8
length :  2


In [14]:
#create 3D array
c=np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

print('dimensions : ',c.ndim)
print('shape : ',c.shape)
print('size : ',c.size) #size is the number of total elements
print('length : ',len(c)) #size of the first dimension

dimensions :  3
shape :  (2, 2, 3)
size :  12
length :  2


In [15]:
c #matrix structure

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
# different Range functions

a = np.arange(10) #default start is '0'
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.arange(5,10) #start and end
b

array([5, 6, 7, 8, 9])

In [19]:
c = np.arange(50, 100, 10) #start, end and step size
c

array([50, 60, 70, 80, 90])

In [21]:
# using linear space function
d = np.linspace(0,1,6) #start, end, no. of points (it equally divides into no. of points given)
d

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [23]:
# use of 'zeros' method

a = np.zeros(2) #int/tuple as argument; creates 1D vector
a 

array([0., 0.])

In [24]:
b = np.zeros((2, 3)) #int/tuple as argument; creates 2D matrix
b 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
c = np.zeros((2, 3, 4)) #creates 3D matrix
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
# use of 'ones' method

a = np.ones(4)
a

array([1., 1., 1., 1.])

In [27]:
b = np.ones((2, 4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
c = np.ones((2, 2, 2))
c

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [29]:
# create identity matrix : a matrix where diagonal elements are one

a = np.eye(2) #2 rows
a

array([[1., 0.],
       [0., 1.]])

In [34]:
b = np.eye(3, 2) #3 rows and 2 columns
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [35]:
c = np.eye(2, 3) #2 rows and 3 columns
c

array([[1., 0., 0.],
       [0., 1., 0.]])

In [36]:
d = np.eye(9, 2) #9 rows and 2 columns
d

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
# construct a diagonal array

a = np.diag([1, 2, 3, 4]) #elements in the list constitute diagonal elements of the matrix
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [38]:
np.diag(a) #extract diagonal elements

array([1, 2, 3, 4])

In [41]:
a = np.array([[1, 2],[5, 6]])  #extract diagonal elements from 2D matrix
np.diag(a)

array([1, 6])

In [46]:
# create random numbers with uniform distribution

a = np.random.rand(5)  # it gives uniform distributed random variables
a

array([0.77740457, 0.36134992, 0.75612012, 0.9525054 , 0.87194263])

In [47]:
# create random numbers which are normal distributed

b = np.random.randn(5)
b

array([-0.49431065, -0.36989414,  0.71376008,  1.6666697 , -0.13321386])

In [48]:
# DataTypes

a = np.arange(5)
a.dtype  #to check datatype

dtype('int32')

In [49]:
#explicit specification of the datatypes

b = np.arange(5, dtype='float64') #type is float
b

array([0., 1., 2., 3., 4.])

In [51]:
# Getting elements by index

print(b[0])  #first element
print(b[2])  #third element
print(b[-1]) #last element 

0.0
2.0
4.0


In [56]:
# getting elements of multi dimensional array
c = np.diag([1, 2, 3, 4])
print(c[2, 2])

3


In [59]:
# assigning values
c[2,2] = 5
np.diag(c) #3 has replaced with 5

array([1, 2, 5, 4])

In [60]:
# SLICING

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a[1:8:2] #1 to 8 with step size of 2

array([1, 3, 5, 7])

In [62]:
a[0:9:3] #0 to 9 with step size of 3

array([0, 3, 6])

In [63]:
# assignment + slicing in combination
a[5:9:1] = 10 
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10,  9])

In [66]:
a[5:] = 5
a

array([0, 1, 2, 3, 4, 5, 5, 5, 5, 5])

In [67]:
a[:9] = 4
a

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 5])

Copies and Views

In [68]:
a = np.arange(10)  # create array
b = a[::2] #assign few elements to another array
b

array([0, 2, 4, 6, 8])

In [69]:
np.shares_memory(a, b) # as are assigned values of one array to another this way they share same memory

True

In [70]:
b[0] = 10
a # we have changed value of element in 'b' but in 'a' also it has changed

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [71]:
a = np.arange(10)  # create array
b = a[::2].copy() #assign few elements to another array using 'copy' function
b

array([0, 2, 4, 6, 8])

In [72]:
np.shares_memory(a, b) # as we have used 'copy' function, which does force copy without sharing same memory location

False

Other different Indexing types

In [77]:
a = np.random.randint(0, 20, 15) #elements from '0' to '20' range and total '15' such numbers
a

array([14, 19, 11,  2, 14, 17,  3,  4,  0,  0, 16, 12,  7,  4, 14])

In [79]:
mask = (a % 2 == 0)
b = a[mask] # or a[(a % 2 ==0)]
b

array([14,  2, 14,  4,  0,  0, 16, 12,  4, 14])

In [80]:
a[mask] = -1 #extracted values are assigned with '-1'
a

array([-1, 19, 11, -1, -1, 17,  3, -1, -1, -1, -1, -1,  7, -1, -1])

In [82]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
a[[4, 6, 8, 10]] #only selected indices can be fetched

array([ 4,  6,  8, 10])

In [84]:
a[[4, 7]] = -1000 #selected indices canbe fetched and assigned new values
a

array([    0,     1,     2,     3, -1000,     5,     6, -1000,     8,
           9,    10,    11,    12,    13,    14])

Other NumPy Operations

In [89]:
a = np.array([2, 5, 7, 9], dtype='int64')
a + 1  # scalar addition

array([ 3,  6,  8, 10], dtype=int64)

In [90]:
a**2

array([ 4, 25, 49, 81], dtype=int64)

In [91]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [92]:
a - b

array([0., 3., 5., 7.])

In [93]:
a * b # does element wise multiplication

array([ 4., 10., 14., 18.])

In [94]:
# matrix multiplication

c = np.diag([1, 2, 3, 4])
print(c * c)
print('****************')
print(c.dot(c))  # both multiplication results same

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [95]:
# array comparison

a = np.array([2, 4, 6, 8])
b = np.array([4, 4, 6, 7])

a == b  # element-wise comparison of values

array([False,  True,  True, False])

In [96]:
a > b # we can also use greater than or less than condition

array([False, False, False,  True])

In [97]:
a < b

array([ True, False, False, False])

In [98]:
# array-wise comparison

a = np.array([2, 4, 6, 8])
b = np.array([1, 4, 6, 7])
c = np.array([2, 4, 6, 8])

np.array_equal(a, b) # compares whole array with another array

False

In [99]:
np.array_equal(a, c) # if all elements are same then only it output as True

True

In [100]:
# logical operations

a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [102]:
np.logical_and(a, b)

array([ True, False, False, False])

In [107]:
# use of 'sin' function
a = np.arange(1, 5, 1)
print(a)
np.sin(a)

[1 2 3 4]


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [108]:
# use of log function
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [109]:
# use of exp function, which is e^x
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [111]:
# use of 'sum' function
a = np.array([2, 4, 6, 8, 10])
np.sum(a)

30

In [119]:
a = np.array([[2, 4],[5, 6]])
np.sum(a, axis=0) #column-wise sum

array([ 7, 10])

In [120]:
# other way of doing same
a.sum(axis=0)

array([ 7, 10])

In [121]:
a.sum(axis=1) #row-wise sum

array([ 6, 11])

In [122]:
# use of 'min' function
a = np.array([2, 4, 6, 8, 10])
a.min() #minimum value

2

In [123]:
a.max() #maximum value

10

In [124]:
# function to get index of minimum element
a.argmin()

0

In [125]:
# function to get index of maximum element
a.argmax()

4

In [126]:
# other logical operations
np.all([True, True, False]) #outputs True if all of them are True

False

In [127]:
np.all([True, True, True])

True

In [128]:
np.any([True, False, True]) #outputs as True if any of them are True

True

In [130]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [133]:
#use of 'any' function in other way
np.any(a != 0)

False

In [134]:
# use of 'all' function in other way
np.all(a == 0)

True

In [135]:
np.all(a == a)

True

In [136]:
#complex comparison for array elements
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 3, 5])
c = np.array([3, 4, 5, 6])
((a<=b) & (c>=b)).all()

True

In [158]:
#Flattening
a = np.array([[2, 4, 6, 8],[4, 6, 8, 9]])
a

array([[2, 4, 6, 8],
       [4, 6, 8, 9]])

In [ ]:
a.ravel() #flattens all rows and columns

In [159]:
#transpose of an array
a.T

array([[2, 4],
       [4, 6],
       [6, 8],
       [8, 9]])

In [160]:
# both transponse and ravel function together
a.T.ravel()

array([2, 4, 4, 6, 6, 8, 8, 9])

In [163]:
# reshaping function
print(a)
b = a.ravel()
print(b)
print('********************')
print(b.reshape(2, 4))
print('********************')
print(b.reshape(4, 2))

[[2 4 6 8]
 [4 6 8 9]]
[2 4 6 8 4 6 8 9]
********************
[[2 4 6 8]
 [4 6 8 9]]
********************
[[2 4]
 [6 8]
 [4 6]
 [8 9]]


In [164]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [167]:
# sorting function
a = np.array([2, 4, 1, 6])
a.sort()
a

array([1, 2, 4, 6])

In [169]:
# argsort function returns indexes after sort
a = np.array([2, 4, 1, 6])
b = a.argsort()
b

array([2, 0, 1, 3], dtype=int64)

<b>Statistical Operations</b>

In [141]:
x = np.array([1, 4, 6, 2])
print('mean : ',x.mean()) #mean of array 'x'
print('median : ',np.median(x)) #median of array 'x'
print('std dev : ',np.std(x)) #std dev od array 'x'

mean :  3.25
median :  3.0
std dev :  1.920286436967152


In [142]:
np.mean(x) #other way of 'mean' function

3.25

In [145]:
y = np.array([[1, 2, 4],[4, 5, 6]])
print(np.mean(y, axis=0)) #column-wise
print(np.median(y, axis=1)) #row-wise
print(np.std(y, axis=1)) #row-wise

[2.5 3.5 5. ]
[2. 5.]
[1.24721913 0.81649658]


<b>Data manipulation by loading a file</b>

In [146]:
# The text file describes populations of hares, lynxes and carrots in northers Canada during 20 years
data = np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [150]:
year, hares, lynxes, carrots = data.T #reading columns to variables
print('***************************year*****************************')
print(year)
print('**************************hares******************************')
print(hares)
print('**************************lynxes******************************')
print(lynxes)
print('***************************carrots*****************************')
print(carrots)

***************************year*****************************
[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]
**************************hares******************************
[30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]
**************************lynxes******************************
[ 4000.  6100.  9800. 35200. 59400. 41700. 19000. 13000.  8300.  9100.
  7400.  8000. 12300. 19500. 45700. 51100. 29700. 15800.  9700. 10100.
  8600.]
***************************carrots*****************************
[48300. 48200. 41500. 38200. 40600. 39800. 38600. 42300. 44500. 42100.
 46000. 46800. 43800. 40900. 39400. 39000. 36700. 41800. 43300. 41300.
 47300.]


In [151]:
populations = data[:,1:] #rows:columns -> all rows and from second column onwards all data
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [155]:
print(populations.mean(axis=0)) #mean of column 1 -> hares population
print(np.median(populations, axis=0)) #median of column 1 -> lynxes population
print(populations.std(axis=0)) #std dev of column 1 -> carrots population

[34080.95238095 20166.66666667 42400.        ]
[25400. 12300. 41800.]
[20897.90645809 16254.59153691  3322.50622558]


In [156]:
#WHICH SPECIES HAS THE HIGHEST POPULATION EACH YEAR??
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)